

version: "3.8"

services:
  server:
    build: .
    container_name: server
    command: python server.py
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    expose: 
      - '5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=fortstats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin


